###
GET http://localhost:3000/grupo/10005

###
GET http://localhost:3000/grupo/all

###
POST http://localhost:3000/grupo  HTTP/1.1
content-type: application/json

{
    "nome" : "Dannyrooh"
}

###
POST http://localhost:3000/grupo  HTTP/1.1
content-type: application/json

{
    
}

###
PUT http://localhost:3000/grupo  HTTP/1.1
content-type: application/json

{
    "id" : 10005,
    "nome" : "João de Deus"
}

###
PUT http://localhost:3000/grupo  HTTP/1.1
content-type: application/json

{
    "id" : 0,
    "nome" : "João de Deus"
}


###
PUT http://localhost:3000/grupo  HTTP/1.1
content-type: application/json

{
    "id" : 0,
    "nome" : ""
}


###
DELETE http://localhost:3000/grupo/1000  
